name: 'Check semantic for releases'
description: 'Check if CURRENT_REF follows defined conventions'
author: 'gbh-tech'
branding:
  icon: 'info'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Determine if current git ref follows the convention
      shell: bash -leo pipefail {0}
      run: |
        CURRENT_REF=${GITHUB_REF##*/}
        REGEX_PRODUCTION="^v([0-9]+\.[0-9]+\.[0-9]+)$"
        REGEX_UAT="^v([0-9].[0-9].[0-9])(-uat.[0-9]{1,2})$"

        echo "Current git reference : ${CURRENT_REF}"

        if ! [[ $CURRENT_REF =~ $REGEX_PRODUCTION || $CURRENT_REF =~ $REGEX_UAT ]]; then
            echo "Error:"
            echo "The tag created for this deployment does not match defined conventions."
            echo "Check the README's 'Releases and deployments' section for more details."
            exit 1
        fi
        echo "The tag created for this deployment follows the defined conventions."

